### ISSUE TITLE
beta for Live 11

### ISSUE THREAD

**Issue by higaru2** [adamjmurray/ableton-midi-sculptor#5]
hello Adam
and big thanks for this fantastic tool.
I just installed the latest build for Live 11 and
it doesnt work at all here. I mean it shows but
it doesnt modify the selected notes at all.
any ideas...?! (Live 11.0.2 on Mac)
thanks!

**Comment by higaru2** [comment]
funny fact:
if I draw (pen) new notes or modify the previous- Sculptor will work on them!
but it wont modify the untouched and selected...

**Comment by higaru2** [comment]
more testing:
sometimes it works, sometimes it doesnt...
but thats why it is beta :)
looking fwd for the updates.
really fantastic creative tool this!
thanks.

**Comment by higaru2** [comment]
well I guess I have found the problem!
maybe you can check.
it seems that the number of notes in selection is somehow limited so
if the note selection is larger than xxx notes, Sculptor wont do anything...
works on on small selections but it doesnt work at all on large ones.

thanks.

**Comment by adamjmurray** [comment]
Hi, I'm sorry for never responding to this. 

Thanks for giving all this feedback. This was indeed a major issue with the device. I had the same problems. It was due to a limitation of the Live API in Live 11.0.* and there wasn't really anything I could do about it. It didn't let us access a lot of notes at once. I think this happened because MPE support is in 11 and the notes contain a lot more data as a result.

Thankfully, Ableton recognized this was a problem and the maximum number of notes supported by the API increased significantly in Live 11.1. 

If you have the latest version of Live, it should be working a lot better than when you tried before. This issue stopped being a problem for me, and I sometimes use it with some pretty busy drum clips.

**Comment by adamjmurray** [comment]
I did some thorough testing with [v2.0 beta 2](https://github.com/adamjmurray/ableton-midi-sculptor/blob/master/releases/2.0-beta-2/Sculptor.amxd?raw=true) of this device with the latest Ableton Live 11.1 beta. I was able to randomize a clip with over 1500 notes in it:

<img width="1447" alt="Screen Shot 2022-01-26 at 12 27 28 AM" src="https://user-images.githubusercontent.com/12264/151128957-e88ecebb-3774-4aca-b958-f59d168dd731.png">
 
The performance was absolutely terrible: it made Live hang for about 5-10 seconds, but it worked! I think it will be fine for normal usage.

I forget if Ableton fixed the underlying issue in Live 11.0.5 or if it's only fixed in Live 11.1 (I only have 11.1 beta on this machine at the moment). Anyway, there isn't anything I can do to fix this in earlier versions, so I'm going to close this GitHub issue. Once Live 11.1 officially releases, I think it's safe to say it's fixed.
